name: CHAOSS Blog RSS Feed

on:
  push:
  schedule:
    - cron: "1 0 * * *"

jobs:
  gene-rss:
    runs-on: ubuntu-latest
    name: A job to gene RSS
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test Rssify
      uses: tabhub/rssify@master
      with:
        title: CHAOSS Blog RSS
        url: https://chaoss.community/blog/
        item-title-css: .title > a
        item-url-css: .title > a
